name: "Run tests"

on: # events on which the worflow should be triggered and on which branches
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: # what we want to do with the test
  build:
    runs-on: ${{ matrix.os }} # specify operation system to run on it
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-10.15, windows-2019]
    steps: # actual commands to run in the test workflow
    - name: Cache pip
      id: myCachePip
      uses: actions/cache@v2
      env:
        cache-name: cache-pip
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.cache/pip
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pip
      if: steps.myCachePip.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v
    - uses: iterative/setup-dvc@v1 # action
    - name: Get data # action
      run: | # command to run
        dvc pull
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
